### ISSUE TITLE
Invalid http resoponse on error.

### ISSUE THREAD

**Issue by Dennor** [Syncano/syncano-node#51]
### Expected behaviour

```
HTTP/1.1 500 Internal Server Error
Server: nginx
Content-Type: text/plain; charset=utf-8
Content-Length: 692
Connection: keep-alive
Keep-Alive: timeout=20
Date: Thu, 30 Nov 2017 10:01:38 GMT

{"id":3,"executed_at":"2017-11-30T10:01:38.029762Z","status":"failure","duration":10,"result":{"stdout":"","stderr":"{ module.js:471\n    throw err;\n    ^\n\nError: Cannot find module 'bar'\n    at Function.Module._resolveFilename (module.js:469:15)\n    at Function.Module._load (module.js:417:25)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at fail-case.js:11:12\n    at ContextifyScript.Script.runInContext (vm.js:35:29)\n    at processScript (/app/wrapper/node.js:133:22)\n    at Socket.\u003canonymous\u003e (/app/wrapper/node.js:191:5)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7) code: 'MODULE_NOT_FOUND' }\n"}}
```

Expected 500 (or better suited one) http response code.

### Actual behaviour

```
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/plain; charset=utf-8
Content-Length: 692
Connection: keep-alive
Keep-Alive: timeout=20
Date: Thu, 30 Nov 2017 10:01:38 GMT

{"id":3,"executed_at":"2017-11-30T10:01:38.029762Z","status":"failure","duration":10,"result":{"stdout":"","stderr":"{ module.js:471\n    throw err;\n    ^\n\nError: Cannot find module 'bar'\n    at Function.Module._resolveFilename (module.js:469:15)\n    at Function.Module._load (module.js:417:25)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at fail-case.js:11:12\n    at ContextifyScript.Script.runInContext (vm.js:35:29)\n    at processScript (/app/wrapper/node.js:133:22)\n    at Socket.\u003canonymous\u003e (/app/wrapper/node.js:191:5)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7) code: 'MODULE_NOT_FOUND' }\n"}}
```

#### socket.yml
```yaml
name: fail-case
description: Description of fail-case
version: 0.0.1

endpoints:
  fail-case:
    file: fail-case.js
    description: Bad script
    parameters:
    response:
```

#### src/fail-case.js

```javascript
import Server from 'syncano-server';
import foo from 'bar';

export default async ctx => {
  const {response} = Server(ctx);
  return response.json({hello: 'world'});
};
```

#### package.json
```json
{
  "license": "MIT",
  "dependencies": {
    "syncano-server": "beta"
  },
  "devDependencies": {
    "eslint": "^4.12.1"
  }
}
```

#### npx s version
```
0.53.0
```
Obviously script has a bad module called 'bar'. The script execution will fail because of that. I would expect http response contain an error code. Maybe 500 Internal Server Error?

**Comment by mkucharz** [comment]
@23doors maybe we should change response code for scripts exceptions?

**Comment by 23doors** [comment]
@mkucharz Seems to make sense. I'll create a task for it.

**Comment by 23doors** [comment]
fixed!
