### ISSUE TITLE
@syncano/cli not working

### ISSUE THREAD

**Issue by gbielecki** [Syncano/syncano-node#78]
I installed @syncano/cli, but cannot run syncano-cli. I am using windows powershell. Please see below. 

D:\Repos\syncanoCanary\socketIdeas> npm install -g @syncano/cli
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
C:\Users\Dell\AppData\Roaming\npm\s -> C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\cli.js
C:\Users\Dell\AppData\Roaming\npm\syncano-cli-hosting -> C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\cli-hosting.js
C:\Users\Dell\AppData\Roaming\npm\syncano-cli -> C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\cli.js
C:\Users\Dell\AppData\Roaming\npm\s-hosting -> C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\cli-hosting.js
+ @syncano/cli@0.4.1
added 427 packages in 19.916s

PS D:\Repos\syncanoCanary\socketIdeas> s
module.js:557
    throw err;
    ^

Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\utils\compile\compile.js:27:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\utils\compile\index.js:7:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\utils\sockets\sockets.js:91:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\utils\sockets\index.js:7:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\utils\session.js:52:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\program\program.js:21:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\program\index.js:7:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Dell\AppData\Roaming\npm\node_modules\@syncano\cli\lib\cli.js:16:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

**Comment by mkucharz** [comment]
@gbielecki please use `@syncano/cli@canary` for now
